title: Random Thoughts
author: N. J. Watkins
description: A blog featuring essays at the intersection of my interests: math, programming, music, and literature.
theme: minima
markdown: kramdown
kramdown:
  math_engine: mathjax